ARG ARCH
FROM --platform=${TARGETPLATFORM} certbot/certbot:${ARCH}-latest

ARG TARGETPLATFORM

LABEL maintainer="docker@carlesbarreda.cat"

RUN apk add --no-cache git \
    && pip install git+https://github.com/rdrgzlng/certbot-dns-dinahosting.git@master

VOLUME ["/etc/letsencrypt"]
VOLUME ["/var/lib/letsencrypt"]
VOLUME ["/var/log/letsencrypt"]
