ARG ARCH
FROM --platform=${TARGETPLATFORM} certbot/certbot:${ARCH}-latest

ARG TARGETPLATFORM

LABEL maintainer="docker@carlesbarreda.cat"

RUN pip install https://github.com/rdrgzlng/certbot-dns-dinahosting/tarball/master

VOLUME ["/etc/letsencrypt"]
VOLUME ["/var/lib/letsencrypt"]
VOLUME ["/var/log/letsencrypt"]
