#!/bin/bash


TAGS=$(curl -s https://hub.docker.com/v2/repositories/certbot/certbot/tags | jq '.results[] | {(.name): .images[].digest}')
DIGEST=$(echo $TAGS | jq . | awk -F': ' '/"latest"/ { print $2 }')
RELEASE=$(echo $TAGS | jq . | grep $DIGEST | egrep -v 'latest|amd64' | cut -d'"' -f2)

echo $RELEASE

env
