#!/bin/bash

apt-get install -y jq

TAGS=$(curl -s https://hub.docker.com/v2/repositories/certbot/certbot/tags | jq '.results[] | {(.name): .images[].digest}')
DIGEST=$(echo $TAGS | jq . | awk -F': ' '/"latest"/ { print $2 }')
RELEASE=$(echo $TAGS | jq . | grep $DIGEST | egrep -v 'latest|amd64' | cut -d'"' -f2)

DOCKER_BUILDKIT=1 docker buildx build \
    --tag ${IMAGE_NAME} \
    --tag ${DOCKER_REPO}:amd64-${$RELEASE} \
    --build-arg ARCH=amd64 \
    --platform linux/amd64 \
    --progress=plain \
    --push \
    .