name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build --tag carlesbarreda/certbot:amd64-latest --build-arg ARCH=amd64 .
        docker push carlesbarreda/certbot:amd64-latest
        docker build --tag carlesbarreda/certbot:arm64v8-latest --build-arg ARCH=arm64v8 .
        docker push carlesbarreda/certbot:arm64v8-latest
        docker build --tag carlesbarreda/certbot:arm32v6-latest --build-arg ARCH=arm32v6 .
        docker push carlesbarreda/certbot:arm32v6-latest
        docker manifest create \
          carlesbarreda/certbot:latest \
          --amend carlesbarreda/certbot:amd64-latest \
          --amend carlesbarreda/certbot:arm64v8-latest \
          --amend carlesbarreda/certbot:arm32v6-latest
        docker manifest push carlesbarreda/certbot:latest
