name: Docker Image CI
on:
  schedule:
    - cron: '55 10 * * *'

  #push:
  #  branches: [ "main" ]
  #  # Publish semver tags as releases.
  #  tags: [ 'v*.*.*' ]

  #pull_request:
  #  branches: [ "main" ]

  #pull_request:
  #  branches:
  #    - main
  #

  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  #REGISTRY: ghcr.io
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  #IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: carlesbarreda/certbot

permissions:
  #contents: read
  contents: write
  packages: write
  # This is used to complete the identity challenge
  # with sigstore/fulcio when running outside of PRs.
  id-token: write
  pull-requests: write
  repository-projects: write

jobs:
  pusher:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Last Docker Image Release
        run: |
          TAGS=$(curl -s https://hub.docker.com/v2/repositories/certbot/certbot/tags | jq '.results[] | {(.name): .images[].digest}')
          DIGEST=$(echo $TAGS | jq . | awk -F': ' '/"latest"/ { print $2 }')
          RELEASE=$(echo $TAGS | jq . | grep $DIGEST | egrep -v 'latest|amd64' | cut -d'"' -f2)
          [ -f VERSION ] && VERSION=$(cat VERSION) || VERSION=""
          [ "$RELEASE" == "$VERSION" ] && exists='true' || exists='false'
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "exists=$exists" >> $GITHUB_ENV

      - name: Check Tag Exists
        uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with: 
          tag: ${{ env.RELEASE }}

      #- name: Check VERSION Exists
      #  id: checkTag
      #  run: |
      #    [ '${{ env.RELEASE }}' == '${{ env.VERSION}}' ] && exists='true' || exists='false'
      #    echo "exists=$exists" >> $GITHUB_OUTPUT
      #    echo $exists

      - name: Check If Need Build
        run: |
          [[ '${{ env.RELEASE }}' != '${{ env.VERSION}}' && steps.checkTag.outputs.exists != 'true' ]] && BUILD='true' || BUILD='false'
          echo "BUILD=$BUILD" >> $GITHUB_ENV

      - name: Set up QEMU
        if: '${{ env.BUILD }}' == 'true'
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        if: '${{ env.BUILD }}' == 'true'
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        if: steps.checkTag.outputs.exists != 'true' && github.event_name != 'pull_request'
        #uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          #username: ${{ github.actor }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build amd64
        if: steps.checkTag.outputs.exists != 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            TARGETPLATFORM=linux/amd64
            TARGETARCH=amd64
          tags: |
            ${{ env.IMAGE_NAME }}:amd64-${{ env.RELEASE }}
            ${{ env.IMAGE_NAME }}:amd64-latest
          push: true

      - name: Build arm64v8
        if: steps.checkTag.outputs.exists != 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64/v8
          build-args: |
            TARGETPLATFORM=linux/arm64/v8
            TARGETARCH=arm64v8
          tags: |
            ${{ env.IMAGE_NAME }}:arm64v8-${{ env.RELEASE }}
            ${{ env.IMAGE_NAME }}:arm64v8-latest
          push: true

      - name: Build arm32v6
        if: steps.checkTag.outputs.exists != 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v6
          build-args: |
            TARGETPLATFORM=linux/arm/v6
            TARGETARCH=arm32v6
          tags: |
            ${{ env.IMAGE_NAME }}:arm32v6-${{ env.RELEASE }}
            ${{ env.IMAGE_NAME }}:arm32v6-latest
          push: true

      - name: Create tag
        if: steps.checkTag.outputs.exists != 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.RELEASE }}",
              sha: context.sha
            })

      - name: Update VERSION file
        if: steps.checkTag.outputs.exists != 'true'
        run: echo "${{ env.RELEASE }}" > VERSION
      - name: Commit VERSION file
        if: steps.checkTag.outputs.exists != 'true'
        run: |
          git config --global user.name 'Carles Barreda'
          git config --global user.email '9409275+carlesbarreda@users.noreply.github.com'
          git add .
          #git add VERSION
          git commit -am "Automated VERSION"
          git push

      #- name: Create and push manifest release images
      #  if: steps.checkTag.outputs.exists != 'true'
      #  uses: Noelware/docker-manifest-action@master # or use a pinned version in the Releases tab
      #  with:
      #    inputs: carlesbarreda/certbot:${{ env.RELEASE }}
      #    images: carlesbarreda/certbot:amd64-${{ env.RELEASE }},carlesbarreda/certbot:arm64v8-${{ env.RELEASE }},carlesbarreda/certbot:arm32v6-${{ env.RELEASE }}
      #    amend: true
      #    push: true

      #- name: Create and push manifest latest images
      #  if: steps.checkTag.outputs.exists != 'true'
      #  uses: Noelware/docker-manifest-action@master # or use a pinned version in the Releases tab
      #  with:
      #    inputs: carlesbarreda/certbot:latest
      #    images: carlesbarreda/certbot:amd64-latest,carlesbarreda/certbot:arm64v8-latest,carlesbarreda/certbot:arm32v6-latest
      #    amend: true
      #    push: true

      #- name: Build the Docker image release manifest
      #  if: steps.checkTag.outputs.exists != 'true'
      #  env:
      #    DOCKER_CLI_EXPERIMENTAL: enabled
      #  run: |
      #    docker manifest create --amend \
      #      carlesbarreda/certbot:${{ env.RELEASE }} \
      #        carlesbarreda/certbot:amd64-${{ env.RELEASE }} \
      #        carlesbarreda/certbot:arm64v8-${{ env.RELEASE }} \
      #        carlesbarreda/certbot:arm32v6-${{ env.RELEASE }}
      #    docker manifest push carlesbarreda/certbot:${{ env.RELEASE }}

      #- name: Build the Docker image latest manifest
      #  if: steps.checkTag.outputs.exists != 'true'
      #  #if: ${{ github.event.inputs.latest == 'yes' }}
      #  env:
      #    DOCKER_CLI_EXPERIMENTAL: enabled
      #  run: |
      #    docker manifest create --amend \
      #      carlesbarreda/certbot:latest \
      #        carlesbarreda/certbot:amd64-$RELEASE \
      #        carlesbarreda/certbot:arm64v8-$RELEASE \
      #        carlesbarreda/certbot:arm32v6-$RELEASE
      #    docker manifest push carlesbarreda/certbot:latest

      #- name: Remove TARGETARCH tag
      #  if: steps.checkTag.outputs.exists != 'true'
      #  run: |
      #    LOGIN=$(echo -e "{\n  \"username\": \"${{ secrets.DOCKER_USERNAME }}\",\n  \"password\": \"${{ secrets.DOCKER_PASSWORD }}\"\n}\n")
      #    TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "$LOGIN" "https://hub.docker.com/v2/users/login/" | jq -r .token)
      #    curl "https://hub.docker.com/v2/repositories/carlesbarreda/certbot/tags/amd64-latest/" \
      #      -X DELETE \
      #      -H "Authorization: JWT ${TOKEN}"
      #    curl "https://hub.docker.com/v2/repositories/carlesbarreda/certbot/tags/arm64v8-latest/" \
      #      -X DELETE \
      #      -H "Authorization: JWT ${TOKEN}"
      #    curl "https://hub.docker.com/v2/repositories/carlesbarreda/certbot/tags/arm32v6-latest/" \
      #      -X DELETE \
      #      -H "Authorization: JWT ${TOKEN}"
