name: Manual Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Cerbot version tag'
        required: true
        default: 'v1.10.1'
      latest:
        description: 'Is latest?'
        required: true
        default: 'yes'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Set env
      run: echo "RELEASE=${{ github.event.inputs.tags }}" >> $GITHUB_ENV
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    #- name: Build the Docker image amd64
    #  run: docker buildx build --file Dockerfile.buildx --tag carlesbarreda/certbot:amd64-latest --build-arg ARCH=amd64 --platform linux/amd64 --push .
    - name: Build the Docker image arm64v8
      run: docker buildx build --file Dockerfile.buildx --tag carlesbarreda/certbot:arm64v8-latest --build-arg ARCH=arm64v8 --platform linux/arm64 --push .
    - name: Build the Docker image arm32v6
      run: docker buildx build --file Dockerfile.buildx --tag carlesbarreda/certbot:arm32v6-latest --build-arg ARCH=arm32v6 --platform linux/arm/v6 --push .

    - name: Build the Docker image release manifest
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        docker manifest create \
          carlesbarreda/certbot:$RELEASE \
          --amend carlesbarreda/certbot:amd64-latest \
          --amend carlesbarreda/certbot:arm64v8-latest \
          --amend carlesbarreda/certbot:arm32v6-latest
        docker manifest push carlesbarreda/certbot:$RELEASE

    - name: Build the Docker image latest manifest
      if: ${{ github.event.inputs.latest == 'yes' }}
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        docker manifest create \
          carlesbarreda/certbot:latest \
          --amend carlesbarreda/certbot:amd64-latest \
          --amend carlesbarreda/certbot:arm64v8-latest \
          --amend carlesbarreda/certbot:arm32v6-latest
        docker manifest push carlesbarreda/certbot:latest

    #- name: Remove arch tag
    #  run: |
    #    LOGIN=$(echo -e "{\n  \"username\": \"${{ secrets.DOCKER_USERNAME }}\",\n  \"password\": \"${{ secrets.DOCKER_PASSWORD }}\"\n}\n")
    #    TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "$LOGIN" "https://hub.docker.com/v2/users/login/" | jq -r .token)
    #    curl "https://hub.docker.com/v2/repositories/carlesbarreda/certbot/tags/amd64-latest/" \
    #      -X DELETE \
    #      -H "Authorization: JWT ${TOKEN}"
    #    curl "https://hub.docker.com/v2/repositories/carlesbarreda/certbot/tags/arm64v8-latest/" \
    #      -X DELETE \
    #      -H "Authorization: JWT ${TOKEN}"
    #    curl "https://hub.docker.com/v2/repositories/carlesbarreda/certbot/tags/arm32v6-latest/" \
    #      -X DELETE \
    #      -H "Authorization: JWT ${TOKEN}"
